os: osx

env:
  global:
    - HOMEBREW_NO_INSTALL_CLEANUP=1
    - OPAMROOT=$HOME/Library/Caches/Homebrew/opam
    - OPAMYES=1
    - OPAMJOBS=2

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

addons:
  homebrew:
    update: true

jobs:
    include:
        - stage: "build"
          name: "build"
          script:
              - brew test-bot ./Formula/fb-clang.rb
