# File: azure-pipelines.yml

# trigger:
# - master


variables:

  - group: github

  - name: brew_tap_path
    value: /usr/local/Homebrew/Library/Taps

  # Github variables
  - name: github_user_name
    value: Amar Paul
  - name: github_user
    value: Amar1729
  - name: github_email
    value: amar.paul16@gmail.com
  - name: github_token
    value: $(github.token)
  - name: github_tap_repo
    value: homebrew-infer


stages:
  # - template: /.azure-ci/stages/stage-test-formulae.yml
  - stage: stage_build_bottles
    displayName: Stage - Build bottles

    jobs:

      - template: /.azure-ci/jobs/bottles-build.yml
        parameters:
          name: brew_test_bot_macOS_10_14
          displayName: for macOS Mojave (10.14)
          vmImage: macOS-10.14
          xcode: Xcode_10.2

      # lets just run Mojave for now
      # - template: /.azure-ci/jobs/bottles-build.yml
      #   parameters:
      #     name: brew_test_bot_macOS_10_13
      #     displayName: for macOS High Sierra (10.13)
      #     vmImage: macOS-10.13
      #     xcode: Xcode_10.1
